// +build !ignore_autogenerated

// Code generated by operator-sdk. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LineMessengerGateway) DeepCopyInto(out *LineMessengerGateway) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LineMessengerGateway.
func (in *LineMessengerGateway) DeepCopy() *LineMessengerGateway {
	if in == nil {
		return nil
	}
	out := new(LineMessengerGateway)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *LineMessengerGateway) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LineMessengerGatewayList) DeepCopyInto(out *LineMessengerGatewayList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]LineMessengerGateway, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LineMessengerGatewayList.
func (in *LineMessengerGatewayList) DeepCopy() *LineMessengerGatewayList {
	if in == nil {
		return nil
	}
	out := new(LineMessengerGatewayList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *LineMessengerGatewayList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LineMessengerGatewaySpec) DeepCopyInto(out *LineMessengerGatewaySpec) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LineMessengerGatewaySpec.
func (in *LineMessengerGatewaySpec) DeepCopy() *LineMessengerGatewaySpec {
	if in == nil {
		return nil
	}
	out := new(LineMessengerGatewaySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LineMessengerGatewayStatus) DeepCopyInto(out *LineMessengerGatewayStatus) {
	*out = *in
	if in.Nodes != nil {
		in, out := &in.Nodes, &out.Nodes
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LineMessengerGatewayStatus.
func (in *LineMessengerGatewayStatus) DeepCopy() *LineMessengerGatewayStatus {
	if in == nil {
		return nil
	}
	out := new(LineMessengerGatewayStatus)
	in.DeepCopyInto(out)
	return out
}
